# Generated by Django 6.0.5 on 2026-05-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0002_alter_subtask_status_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Subtask'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task'},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='task_manage_name_fefd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['title'], name='task_manage_title_bcba5a_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title'], name='task_manage_title_17ae96_idx'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='task_manager_category',
        ),
        migrations.AlterModelTable(
            name='subtask',
            table='task_manager_subtask',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task_manager_task',
        ),
    ]
