# Generated by Django 6.0.5 on 2026-05-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0003_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='task_manage_name_fefd4d_idx',
        ),
        migrations.RemoveIndex(
            model_name='subtask',
            name='task_manage_title_bcba5a_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_manage_title_17ae96_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
